#!/bin/bash
NAME=ZetaBot
VERSION=0.1.7

ADDFOLDER ZetaCode
ADDFOLDER sprites
ADDFOLDER sounds
ADDFOLDER acs
ADDFOLDER source

ADDFILE CREDITS.txt
ADDFILE CVarInfo.txt
ADDFILE KeyConf.txt
ADDFILE LICENSE
ADDFILE LOADACS
ADDFILE README.md
ADDFILE SNDINFO.txt
ADDFILE ZScript.txt
