NAME=ZetaBot
VERSION=0.1.2

ADDFOLDER ZetaCode
ADDFOLDER Sprites
ADDFOLDER Sounds

ADDFILE CREDITS.txt
ADDFILE CVarInfo.txt
ADDFILE KeyConf.txt
ADDFILE LICENSE
ADDFILE README.md
ADDFILE SNDINFO.txt
ADDFILE ZScript.txt
