NAME=ZetaBot
VERSION=0.1.5

ADDFOLDER ZetaCode
ADDFOLDER Sprites
ADDFOLDER Sounds
ADDFOLDER ACS

ADDFILE CREDITS.txt
ADDFILE CVarInfo.txt
ADDFILE KeyConf.txt
ADDFILE LICENSE
ADDFILE README.md
ADDFILE SNDINFO.txt
ADDFILE ZScript.txt
ADDFILE LoadACS.txt
ADDFILE ZetaACS.acs
