name: Build & Deploy
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt install zip

      - name: Checkout
        uses: actions/checkout@v2

      - name: Package ZetaBot
        run: ./build
      
      - name: Get version
        run: |
          source ./version.sh
          echo "VERSION=$VERSION" >>$GITHUB_ENV
      
      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZetaBot_v${{ env.VERSION }}.pk3
          path: Built/ZetaBot_v${{ env.VERSION }}.pk3

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        run: |
          source ./version.sh
          echo "VERSION=$VERSION" >>$GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ZetaBot_v${{ env.VERSION }}.pk3

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: "v${{ env.VERSION }}"
          draft: true
          bodyFile: changelog/latest.md
          artifacts: ZetaBot_v${{ env.VERSION }}.pk3
          prerelease: contains(github.ref, '-rc')
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive release log
        run: |
          cp changelog/latest.md changelog/archived/v$VERSION.md
      - name: Commit archived log
        uses: EndBug/add-and-commit@v7.2.0
        with:
          add: changelog/archived/v${{ env.VERSION }}.md
          push: "-u origin changelog-archivals"
          pull_strategy: "NO-PULL"
          branch: changelog-archivals
          message: "(CI) Archived changelog for v${{ env.VERSION }}"
